# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-22 16:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Server',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('game', models.CharField(max_length=20)),
                ('rank', models.IntegerField()),
                ('players_online', models.IntegerField()),
                ('location', models.CharField(max_length=20)),
                ('IP', models.CharField(max_length=20)),
                ('map', models.CharField(max_length=20)),
                ('isAlive', models.BooleanField(default=True)),
            ],
        ),
    ]
